# For use with arduino-mk https://github.com/sudar/Arduino-Makefile
#BOARD_TAG    = uno
#MONITOR_PORT = /dev/ttyUSB1
BOARD_TAG    = leonardo
#MONITOR_PORT = /dev/ttyACM0
MONITOR_PORT = /dev/serial/by-path/pci-0000:00:1d.0-usb-0:1.7:1.0
ARDUINO_LIBS =

include /usr/share/arduino/Arduino.mk

